from zope.interface import Interface

class ICourier(Interface):
    async def get_deposit_address(self, coin_address: str) -> str | None: ...
    async def withdraw(self, coin_address: str, amount: float, ex_destination: 'ICourier', tag: str = '') -> bool: ...