from zope.interface import Interface

class ITrader(Interface):
    async def sell(self, coin_name: str, usdt_quantity: float | None = None) -> None: ...
    async def buy(self, coin_name: str, amount: float | None = None) -> None: ...